spring:
  config:
    import: optional:file:.env[.properties]  # .env 파일 로드
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    tracer: TRACE
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace